/* In Class-7 – ex 02 – COSC 2328 – Professor McCurry 
 Implemented by - Analee Maharaj  */

 /*ex 9.2 step 2 */
 const msg = document.getElementById('msg');
 msg.value = "this test is generated by Javascript";
 
/*ex 9.2 step 3 */
 //const legend = document.getElementById('title');
 //legend.textContent = "Dynamically generated in Step 3";
 
 /* ex 9.2 step 4 */
 document.getElementById("title").textContent = "Dynamically generated in Step 4";

 /* ex 9.2 step 5 */
 document.getElementById("title").textContent = "Dynamically <span> dynamically added span element </span> generated in Step 5";
 
 /* ex 9.2 step 6*/
 const legend_06 = document.getElementById("title");
 legend_06.innerHTML = "Dynamically generated <span>dynamically added span elements</span> in step 6";
 document.getElementById("title").innerHTML = legend_06.innerHTML;

/* ex 9.2 step 7 */
window.addEventListener('DOMContentLoaded', function () {
    const inputLabels = document.querySelectorAll('.input-labels');
    
    inputLabels.forEach(function (element) {
      element.style.backgroundColor = 'Moccasin';
    });
  });

/* ex 9.2 step 8 */

window.addEventListener('DOMContentLoaded', function () {
    const msgElement = document.getElementById('msg');
    msgElement.style.color = 'blue';
  });

/* ex 9.2 step 9 */
const inputlabels= document.querySelectorAll('input[type=text]');

for (let inputs of inputlabels){
  inputs.style.backgroundColor="#E4F0F5";
}

/* ex 9.2 step 10 */
const dispTxtArea = document.querySelector('#msg').value;
alert(dispTxtArea);

/* ex 9.2 step 11 */
const dispTxtAreaBad = document.querySelector('#msg000');
alert(dispTxtAreaBad);

/* ex 9.2 step 12*/

//assign the information associated with the id="thumb-list" to the variable imgList?
const imgList = document.querySelector("#thumb-list");
//create variable, listItem, that contains a list element?
const li = document.createElement("li");
//create variable, img, that contains a img element?
// set the attributes of img to the image 8710320515.jpg?
//nest img within our listItem (our list element)?

const img = document.createElement("img");
img.setAttribute("src", "images/8710320515.jpg");
img.setAttribute("alt", " this image we added ");
li.appendChild(img);
//imgList.appendChild(li);

/* ex 9.2 step 13*/
//add img to the start of our listItem (our list element)?
imgList.insertAdjacentElement("afterbegin", img);

/* ex 9.2 step 14*/
//dynamic remove the last item from the list

//imgList.removeChild(imgList.lastChild);
const removeElements = document.querySelectorAll('.thumbs');
removeElements[removeElements.length - 1].remove();


/* ex 9.2 step 15*/




 

